### PR TITLE
set up appveyor testing

### LINKED ISSUE #38: appveyor testing is not set up
Looking for someone to figure out how to configure appveyor testing for this repo. I've added the project to the `UptakeOpenSource` account with appveyor, just need someone to figure out how to create the `.appveyor.yml` that will run our tests

### PR DESCRIPTION
**Pull request by BruceZhaoR**
fixes  #38

### CODE REVIEW

**Comment by jameslamb** [comment]
Thanks @BruceZhaoR ! Let me go activate this project in the appveyor repo and try to build the branch

**Comment by jameslamb** [comment]
Could you please add `(fixes #38)` to the title so GitHub will automatically close that issue when we merge this?

**Comment by jameslamb** [comment]
@BruceZhaoR could you push one more commit (now that I have it watching the repo) to trigger a build?

**Comment by jameslamb** [comment]
@BruceZhaoR WOO IT WORKED!

https://ci.appveyor.com/project/jameslamb/pkgnet/builds/23832679

**Comment by BruceZhaoR** [comment]
@jameslamb  you need to modify 
`[AppVeyor build status](https://ci.appveyor.com/project/jameslamb/pkgnet)`
 to README

**Comment by jameslamb** [comment]
Ah! I merged too quickly!

Thank you

**Pull request merged**
